apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: neon-brick-breaker
spec:
  owner:
    projectName: default

  # References the ComponentType
  componentType: deployment/web-application

  autoDeploy: true

  # Component Workflow configuration (developer-provided)
  workflow:
    # Reference to ComponentWorkflow
    name: react

    # Required parameters required by the ComponentWorkflow
    systemParameters:
      repository:
        url: "https://github.com/SENATH/neon-brick-breaker"
        revision:
          branch: "main"
          # Optional commit hash, should be a valid git commit
          # commit: ""
        appPath: "/"

    # Developer-configurable parameters (defined by PE, passed to build plane resource)
    parameters:
      nodeVersion: "24"

  parameters:
    replicas: 2
    port: 80
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

---
apiVersion: openchoreo.dev/v1alpha1
kind: ComponentWorkflowRun
metadata:
  name: neon-brick-breaker-build-01
spec:
  # Ownership tracking for the component workflow execution (required)
  owner:
    projectName: default
    componentName: neon-brick-breaker

  workflow:
    # Reference to ComponentWorkflow
    name: react

    # Required system parameters
    systemParameters:
      repository:
        url: "https://github.com/SENATH/neon-brick-breaker"
        revision:
          branch: "main"
          # Optional commit hash, should be a valid git commit
          # commit: "" 
        appPath: "/"

    # Developer-configurable parameters (defined by PE, passed to build plane resource)
    parameters:
      nodeVersion: "24"
